
page: str = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
    :root {{
        --thumb-w: 300px;
        --thumb-h: 200px;
        --glow-color: rgba(128, 128, 128, 0.85);
    }}

    * {{
        box-sizing: border-box;
    }}

    body {{
        margin: 0;
        padding: 40px 20px;
        min-height: 100vh;
        background: #ffffff;
        color: #222;
        font-family: "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        display: flex;
        flex-direction: column;
        align-items: center;
    }}

    h1 {{
        margin-bottom: 10px;
        font-weight: 300;
        letter-spacing: 1px;
        text-align: center;
        color: #222;
    }}

    section.folder-section {{
        width: 100%;
        max-width: calc(6 * var(--thumb-w) + 5 * 28px);
        margin-top: 50px;
    }}

    section.folder-section:first-of-type {{
        margin-top: 30px;
    }}

    h2.folder-heading {{
        font-weight: 400;
        font-size: 1.4rem;
        text-align: center;
        color: #222;
        border-bottom: 2px solid #eee;
        padding-bottom: 12px;
        margin-bottom: 26px;
    }}

    .gallery {{
        /* Centered, responsive grid: columns auto-adjust to window width,
           but never exceed 6 columns. */
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(220px, var(--thumb-w)));
        gap: 28px;
        justify-content: center;
        width: 100%;
    }}

    .thumb-link {{
        display: block;
        width: 100%;
        aspect-ratio: 3 / 2;
        border-radius: 10px;
        overflow: hidden;
        text-decoration: none;
        cursor: zoom-in;
        transition: transform 0.25s ease, box-shadow 0.25s ease;
        box-shadow: 0 0 12px 2px var(--glow-color);
    }}

    .thumb-link:hover,
    .thumb-link:focus {{
        transform: translateY(-4px) scale(1.03);
        box-shadow: 0 0 26px 8px var(--glow-color);
    }}

    .thumb-link img {{
        width: 100%;
        height: 100%;
        object-fit: cover;
        display: block;
    }}

    .caption {{
        margin-top: 8px;
        font-size: 0.85rem;
        color: #666;
        text-align: center;
        word-break: break-word;
    }}

    .empty {{
        text-align: center;
        color: #888;
        font-size: 1rem;
    }}

    footer {{
        margin-top: 50px;
        color: #999;
        font-size: 0.8rem;
        text-align: center;
    }}

    /* Lightbox overlay: expands the clicked image to fill the screen */
    .lightbox {{
        display: none;
        position: fixed;
        inset: 0;
        background: rgba(0, 0, 0, 0.9);
        z-index: 1000;
        align-items: center;
        justify-content: center;
        cursor: zoom-out;
        animation: fadeIn 0.2s ease;
    }}

    .lightbox.open {{
        display: flex;
    }}

    .lightbox-content {{
        display: flex;
        flex-direction: column;
        align-items: center;
        max-width: 92vw;
        max-height: 92vh;
        cursor: default;
    }}

    .lightbox-content img {{
        max-width: 92vw;
        max-height: 82vh;
        object-fit: contain;
        border-radius: 6px;
        box-shadow: 0 0 40px 10px rgba(0, 0, 0, 0.6);
        display: block;
    }}

    .lightbox-caption {{
        margin-top: 16px;
        color: #fff;
        font-size: 1rem;
        text-align: center;
        max-width: 92vw;
        word-break: break-word;
    }}

    .lightbox-close {{
        position: fixed;
        top: 18px;
        right: 28px;
        font-size: 2.2rem;
        color: #fff;
        line-height: 1;
        cursor: pointer;
        user-select: none;
        opacity: 0.85;
    }}

    .lightbox-close:hover {{
        opacity: 1;
    }}

    .lightbox-arrow {{
        position: fixed;
        top: 50%;
        transform: translateY(-50%);
        font-size: 3rem;
        color: #fff;
        cursor: pointer;
        user-select: none;
        opacity: 0.7;
        padding: 10px 18px;
        line-height: 1;
        z-index: 1001;
    }}

    .lightbox-arrow:hover {{
        opacity: 1;
    }}

    .lightbox-arrow.left {{
        left: 10px;
    }}

    .lightbox-arrow.right {{
        right: 10px;
    }}

    .lightbox-arrow.hidden {{
        display: none;
    }}

    @keyframes fadeIn {{
        from {{ opacity: 0; }}
        to {{ opacity: 1; }}
    }}
</style>
</head>
<body>
<h1>{title}</h1>
{sections}
<footer>Generated by generate_gallery.py &middot; {folder_count} folder(s) &middot; {total_count} image(s)</footer>

<div class="lightbox" id="lightbox" onclick="closeLightbox()">
    <span class="lightbox-close" onclick="closeLightbox()">&times;</span>
    <span class="lightbox-arrow left" id="lightbox-prev" onclick="prevImage(event)">&#10094;</span>
    <div class="lightbox-content" onclick="event.stopPropagation()">
        <img id="lightbox-img" src="" alt="">
        <div class="lightbox-caption" id="lightbox-caption"></div>
    </div>
    <span class="lightbox-arrow right" id="lightbox-next" onclick="nextImage(event)">&#10095;</span>
</div>

<script>
    const GALLERIES = {galleries_json};
    let curSection = -1;
    let curIndex = -1;

    function showImage() {{
        const list = GALLERIES[curSection];
        const item = list[curIndex];
        const img = document.getElementById('lightbox-img');
        const caption = document.getElementById('lightbox-caption');
        img.src = item.src;
        img.alt = item.alt;
        caption.textContent = item.alt;

        const prevBtn = document.getElementById('lightbox-prev');
        const nextBtn = document.getElementById('lightbox-next');
        prevBtn.classList.toggle('hidden', curIndex <= 0);
        nextBtn.classList.toggle('hidden', curIndex >= list.length - 1);
    }}

    function openLightbox(section, index) {{
        curSection = section;
        curIndex = index;
        const lb = document.getElementById('lightbox');
        showImage();
        lb.classList.add('open');
        document.body.style.overflow = 'hidden';
    }}

    function closeLightbox() {{
        const lb = document.getElementById('lightbox');
        lb.classList.remove('open');
        document.body.style.overflow = '';
    }}

    function prevImage(event) {{
        event.stopPropagation();
        if (curIndex > 0) {{
            curIndex -= 1;
            showImage();
        }}
    }}

    function nextImage(event) {{
        event.stopPropagation();
        const list = GALLERIES[curSection];
        if (curIndex < list.length - 1) {{
            curIndex += 1;
            showImage();
        }}
    }}

    document.addEventListener('keydown', function (e) {{
        const lb = document.getElementById('lightbox');
        if (!lb.classList.contains('open')) return;
        if (e.key === 'Escape') {{
            closeLightbox();
        }} else if (e.key === 'ArrowLeft') {{
            prevImage(e);
        }} else if (e.key === 'ArrowRight') {{
            nextImage(e);
        }}
    }});
</script>
</body>
</html>
"""

section: str = """<section class="folder-section">
    <h2 class="folder-heading">{folder_name}</h2>
    {content}
</section>
"""

item: str = """    <figure style="margin:0;">
        <a class="thumb-link" href="{original_href}" onclick="openLightbox({section_idx}, {item_idx}); return false;">
            <img src="{thumb_href}" alt="{alt}" loading="lazy">
        </a>
        <figcaption class="caption">{alt}</figcaption>
    </figure>
"""
